In [18]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
df = pd.read_csv("healthcare_analytics_patient_flow_data.csv")

df

,Patient Id,Patient Admission Date,Patient Admission Time,Merged,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime
0,780-96-6113,9/9/2024,9:25:00 AM,W. Breede,Female,63,African American,NaN,Not Admission,5.0,32
1,714-35-6722,9/9/2024,4:42:00 PM,Y. Baldetti,Male,31,Asian,Orthopedics,Not Admission,NaN,22
2,571-85-3714,9/9/2024,12:14:00 AM,M. Semerad,Male,75,White,General Practice,Not Admission,NaN,16
3,404-43-9499,9/9/2024,8:33:00 PM,K. Blaydes,Male,79,African American,General Practice,Admission,NaN,38
4,552-51-5855,9/9/2024,7:25:00 PM,F. Dickerson,Female,24,African American,NaN,Admission,NaN,36
...,...,...,...,...,...,...,...,...,...,...,...
9211,353-25-3957,1/1/2024,11:01:00 PM,S. Levermore,Male,19,White,Cardiology,Not Admission,NaN,34
9212,608-47-0337,1/1/2024,5:25:00 PM,R. Boyle,Female,22,White,Orthopedics,Admission,NaN,45
9213,716-90-5923,1/1/2024,11:42:00 AM,V. Seadon,Female,8,African American,NaN,Admission,NaN,21
9214,641-52-3173,1/1/2024,4:59:00 AM,L. Harford,Female,37,White,NaN,Not Admission,5.0,10
9215,390-79-5650,1/1/2024,5:33:00 PM,E. Skerritt,Male,59,Asian,NaN,Not Admission,NaN,47

In [3]:
df.describe()

       Patient Age  Patient Satisfaction Score  Patient Waittime
count  9216.000000                 2517.000000       9216.000000
mean     39.855143                    4.992054         35.259874
std      22.755125                    3.138043         14.735323
min       1.000000                    0.000000         10.000000
25%      20.000000                    2.000000         23.000000
50%      39.000000                    5.000000         35.000000
75%      60.000000                    8.000000         48.000000
max      79.000000                   10.000000         60.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9216 entries, 0 to 9215
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Patient Id                  9216 non-null   object
 1   Patient Admission Date      9216 non-null   object
 2   Patient Admission Time      9216 non-null   object
 3   Merged                      9216 non-null   object
 4   Patient Gender              9216 non-null   object
 5   Patient Age                 9216 non-null   int64
 6   Patient Race                9216 non-null   object
 7   Department Referral         3816 non-null   object
 8   Patient Admission Flag      9216 non-null   object
 9   Patient Satisfaction Score  2517 non-null   float64
 10  Patient Waittime            9216 non-null   int64
dtypes: float64(1), int64(2), object(8)
memory usage: 792.1+ KB

In [7]:
df.isnull().sum()

Patient Id                       0
Patient Admission Date           0
Patient Admission Time           0
Merged                           0
Patient Gender                   0
Patient Age                      0
Patient Race                     0
Department Referral           5400
Patient Admission Flag           0
Patient Satisfaction Score    6699
Patient Waittime                 0
dtype: int64

In [11]:
std_value = df['Patient Satisfaction Score'].std()
df['Patient Satisfaction Score'].fillna(std_value, inplace=True)

df

C:\Users\hp\AppData\Local\Temp\ipykernel_20560\2438504746.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Patient Satisfaction Score'].fillna(std_value, inplace=True)

,Patient Id,Patient Admission Date,Patient Admission Time,Merged,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime
0,780-96-6113,9/9/2024,9:25:00 AM,W. Breede,Female,63,African American,NaN,Not Admission,5.000000,32
1,714-35-6722,9/9/2024,4:42:00 PM,Y. Baldetti,Male,31,Asian,Orthopedics,Not Admission,3.138043,22
2,571-85-3714,9/9/2024,12:14:00 AM,M. Semerad,Male,75,White,General Practice,Not Admission,3.138043,16
3,404-43-9499,9/9/2024,8:33:00 PM,K. Blaydes,Male,79,African American,General Practice,Admission,3.138043,38
4,552-51-5855,9/9/2024,7:25:00 PM,F. Dickerson,Female,24,African American,NaN,Admission,3.138043,36
...,...,...,...,...,...,...,...,...,...,...,...
9211,353-25-3957,1/1/2024,11:01:00 PM,S. Levermore,Male,19,White,Cardiology,Not Admission,3.138043,34
9212,608-47-0337,1/1/2024,5:25:00 PM,R. Boyle,Female,22,White,Orthopedics,Admission,3.138043,45
9213,716-90-5923,1/1/2024,11:42:00 AM,V. Seadon,Female,8,African American,NaN,Admission,3.138043,21
9214,641-52-3173,1/1/2024,4:59:00 AM,L. Harford,Female,37,White,NaN,Not Admission,5.000000,10
9215,390-79-5650,1/1/2024,5:33:00 PM,E. Skerritt,Male,59,Asian,NaN,Not Admission,3.138043,47

In [36]:
df.describe()

       Patient Age  Patient Satisfaction Score  Patient Waittime
count  9216.000000                 9216.000000       9216.000000
mean     39.855143                    3.644396         35.259874
std      22.755125                    1.836057         14.735323
min       1.000000                    0.000000         10.000000
25%      20.000000                    3.138043         23.000000
50%      39.000000                    3.138043         35.000000
75%      60.000000                    3.138043         48.000000
max      79.000000                   10.000000         60.000000

<h3>Simple Linear Regression</h3>

In [49]:
# from sklearn.model_selection import train_test_split

X = df[['Patient Waittime']]
y = df['Patient Satisfaction Score']

model = LinearRegression()
model.fit(X, y)

y_predict = model.predict(X)

y_predict

new_prediction = np.array([[20]])
print(f"New Prediction : {model.predict(new_prediction)}")

New Prediction : [3.66008938]

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

<h3>Multiple Linear Regression</h3>

In [40]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

In [50]:
X = df[['Patient Gender', 'Patient Age', 'Patient Satisfaction Score', 'Patient Waittime']]
# df = pd.get_dummies(df)
y = df[['Patient Satisfaction Score']]

X_train, X_test, y_train, y_test = train_test_split(
17 X, y, test_size=0.2, random_state=42
18 )

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2897673228.py, line 6)